#!/usr/bin/env python3
"""Glossary reference audit over the phrase audit's six repositories."""
import argparse
import csv
import json
import os
import re
import tempfile
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import unquote

import sys
sys.path.append(str(Path(__file__).resolve().parent.parent / "phrases-audit"))

import run as phrase_audit

HERE = Path(__file__).resolve().parent
ENDPOINT = "https://easyeyes.netlify.app/.netlify/functions/glossary"


def write_key_input(keys):
    if not keys or any(not isinstance(key, str) or not key for key in keys):
        raise ValueError("Glossary must contain nonempty parameter names")
    terms = [f"key = {json.dumps(key, ensure_ascii=True)}" for key in sorted(keys)]
    (HERE / "glossaryKeys.qll").write_text(
        "// Generated by glossary_run.py.\npredicate glossaryKey(string key) {\n  "
        + "\n  or ".join(terms) + "\n}\n", encoding="utf-8"
    )


def data_flow_evidence(matches, repositories=None):
    """Index existing CodeQL paths by key with explicit origin and reader."""
    evidence = {}
    for key in sorted(matches):
        entries = []
        for reference in matches[key]:
            if reference["matchKind"] != "readerDataFlow":
                continue
            for steps in reference["dataFlowPaths"]:
                if not steps:
                    raise ValueError(f"Empty data-flow path for {key}")
                entries.append({
                    "repository": reference["repository"],
                    "commit": (repositories or {}).get(reference["repository"], {}).get("commit"),
                    "method": "codeqlDataFlow",
                    "origin": steps[0],
                    "reader": {name: reference[name] for name in ("path", "line")},
                    "steps": steps,
                })
        if entries:
            evidence[key] = sorted(entries, key=lambda item: (
                item["repository"], item["reader"]["path"], item["reader"]["line"],
                item["origin"]["path"], item["origin"]["line"]
            ))
    return evidence


GLOSSARY_ITERATION_MODEL = '''export const addConditionToData = (
  reader,
  conditionName,
  experiment,
  exclude = ["_calibrateDistanceCheckCm", "_calibrateDistanceCheckLengthCm"],
) => {
  experiment.addData("block_condition", conditionName);
  for (const parameter of Object.keys(getGlossary())) {
    if (
      !exclude.includes(parameter) &&
      getGlossary()[parameter].type !== "obsolete"
    )
      experiment.addData(parameter, reader.read(parameter, conditionName));
  }'''


def glossary_iteration_references(source, payload):
    """Model the source-verified glossary-wide reader without runtime reachability."""
    start = source.find("export const addConditionToData = (")
    if start < 0:
        raise ValueError("addConditionToData missing; review glossary-iteration model")
    section = source[start:]
    if not "".join(section.split()).startswith("".join(GLOSSARY_ITERATION_MODEL.split())):
        raise ValueError("addConditionToData changed; review glossary-iteration model")
    position = source.index("reader.read(parameter, conditionName)", start)
    line = source.count("\n", 0, position) + 1
    lines = source.splitlines()
    excluded = {"_calibrateDistanceCheckCm", "_calibrateDistanceCheckLengthCm"}
    refs = []
    for key, entry in sorted(payload["glossary"].items()):
        if entry["type"] == "obsolete" or key in excluded:
            continue
        refs.append((key, {
            "repository": "threshold", "path": "components/utils.js", "line": line,
            "method": "sourceVerifiedGlossaryIteration", "matchKind": "readerGlossaryIteration",
            "glossaryVersion": payload["version"],
            "loop": "Object.keys(getGlossary())",
            "filters": {"excludedNames": sorted(excluded), "excludedType": "obsolete"},
            "description": "The glossary-key loop supplies this parameter name to reader.read for recording. Runtime reachability is not required by this source-reference audit.",
        }))
    return refs


def grouped_usage(matches, repositories):
    """Group reference evidence under one used category; key sets may overlap."""
    def select_references(kinds):
        selected = {}
        for key in sorted(matches):
            references = [ref for ref in matches[key] if ref["matchKind"] in kinds]
            if references:
                selected[key] = sorted(references, key=lambda ref: (
                    ref["repository"], ref["path"], ref["line"], ref["matchKind"]
                ))
        return selected

    return {
        "directReaderKeys": select_references({"readerLiteral", "readerGlossaryName"}),
        "dataFlowReaderKeys": data_flow_evidence(matches, repositories),
        "otherReferences": select_references({"stringLiteral", "glossaryProperty", "sourceIdentifier", "sourceDefinition", "sourceProperty"}),
        "numberedFamilyReaderKeys": select_references({"readerNumberedFamily"}),
        "glossaryIterationReaderKeys": select_references({"readerGlossaryIteration"}),
    }


def keyed_usage(categories):
    """Show each parameter once, keeping all evidence under that key."""
    keys = set().union(*(set(entries) for entries in categories.values()))
    result = {}
    for key in sorted(keys):
        evidence = {name: entries[key] for name, entries in categories.items() if key in entries}
        result[key] = evidence
    return result


def comment_references(rows, keys, repository):
    """Attach exact comment mentions without promoting them to source usage."""
    keys = sorted(keys, key=lambda key: (-len(key), key))
    if not keys:
        return {}
    pattern = re.compile(r"(?<![A-Za-z0-9_$@])(?:" + "|".join(map(re.escape, keys)) + r")(?![A-Za-z0-9_$@])")
    references = {}
    seen = set()
    for path, start_line, text in rows[1:]:
        for match in pattern.finditer(text):
            key = match.group()
            line = int(start_line) + text.count("\n", 0, match.start())
            identity = (key, path, line)
            if identity in seen:
                continue
            seen.add(identity)
            references.setdefault(key, []).append({
                "repository": repository, "path": path, "line": line,
                "matchKind": "commentMention", "method": "codeqlComment",
                "commentText": text[:1200],
                "description": "Exact parameter name in a source comment; supplementary information only, not usage evidence.",
            })
    return references


def analyze_comments(codeql, workdir):
    result = workdir / "comments.bqrs"
    decoded = workdir / "comments.csv"
    phrase_audit.run(codeql, "query", "run", str(HERE / "glossary-comments.ql"),
                     f"--database={workdir / 'db'}", f"--output={result}")
    phrase_audit.run(codeql, "bqrs", "decode", str(result), "--format=csv", f"--output={decoded}")
    with decoded.open(newline="", encoding="utf-8") as file:
        return list(csv.reader(file))


def report_evidence(value, combine=True):
    """Publish compact locations while preserving ordered data-flow steps."""
    if isinstance(value, dict):
        result = {key: report_evidence(child, combine=key != "steps")
                  for key, child in value.items() if key not in {"method", "matchKind"}}
        if "line" in result:
            lines = result["line"]
            result["line"] = sorted(set(lines if isinstance(lines, list) else [lines]))
        return result
    if isinstance(value, list):
        entries = [report_evidence(child) for child in value]
        if not combine:
            return entries
        result, groups = [], {}
        for entry in entries:
            if not isinstance(entry, dict) or "line" not in entry:
                result.append(entry)
                continue
            identity = json.dumps({key: child for key, child in entry.items() if key != "line"},
                                  sort_keys=True, ensure_ascii=False)
            if identity in groups:
                existing = groups[identity]
                existing["line"] = sorted(set(existing["line"] + entry["line"]))
            else:
                groups[identity] = entry
                result.append(entry)
        return result
    return value


def repository_evidence(entries):
    """Group detailed evidence by repository without repeating snapshot commits."""
    groups = {}
    for entry in report_evidence(entries):
        item = dict(entry)
        repository = item.pop("repository")
        groups.setdefault(repository, []).append(item)
    return groups


def compact_report(report):
    """Keep readable file names and share identical glossary-loop evidence."""
    github_names = {"threshold-scientists": "threshold-scientist", "speaker-calibrator": "speaker-calibration"}
    for name, metadata in report["repositories"].items():
        metadata["github"] = "EasyEyes/" + github_names.get(name, name)
    shared, identities = {}, {}
    for categories in report["used"].values():
        for kind, entries in list(categories.items()):
            if kind == "glossaryIterationReaderKeys":
                names = []
                for entry in entries:
                    item = dict(entry)
                    repository = item.pop("repository")
                    item.pop("description", None)
                    identity = json.dumps({repository: item}, sort_keys=True)
                    if identity not in identities:
                        suffix = str(len(shared) + 1) if shared else ""
                        name = "addConditionToDataGlossaryLoop" + suffix
                        identities[identity] = name
                        shared[name] = {repository: item}
                    name = identities[identity]
                    if name not in names:
                        names.append(name)
                categories[kind] = {"sharedEvidenceNames": names}
            elif kind in {"directReaderKeys", "otherReferences"}:
                groups = {}
                for entry in entries:
                    paths = groups.setdefault(entry["repository"], {})
                    path = entry["path"]
                    paths[path] = sorted(set(paths.get(path, []) + entry["line"]))
                categories[kind] = groups
            else:
                groups = repository_evidence(entries)
                for repository, items in groups.items():
                    snapshot = report["repositories"].get(repository, {}).get("commit")
                    for item in items:
                        if item.get("commit") == snapshot:
                            item.pop("commit")
                categories[kind] = groups
    for entry in report["unused"].values():
        for kind in ("commentReferences", "removalEvidence"):
            if kind in entry:
                entry[kind] = repository_evidence(entry[kind])
    report["sharedEvidence"] = shared
    return report


def separate_obsolete_used(report, glossary):
    """Partition referenced keys by the published glossary type."""
    obsolete = {key for key, definition in glossary.items()
                if definition.get("type") == "obsolete"}
    report["obsoleteUsed"] = {key: evidence for key, evidence in report["used"].items()
                              if key in obsolete}
    report["used"] = {key: evidence for key, evidence in report["used"].items()
                      if key not in obsolete}
    sections = ("obsoleteUsed", "unused", "used")
    report["counts"] = {"total": report["counts"]["total"],
                        **{section: len(report[section]) for section in sections}}
    return {key: value for key, value in report.items() if key not in sections} | {key: report[key] for key in sections}


def flatten_used_locations(report):
    """Publish source locations without detection categories or flow metadata."""
    shared = report.get("sharedEvidence", {})
    for section in ("used", "obsoleteUsed"):
        for key, categories in report.get(section, {}).items():
            locations = {}

            def collect(value, repository):
                if isinstance(value, dict):
                    if "path" in value and "line" in value:
                        paths = locations.setdefault(repository, {})
                        path = value["path"]
                        lines = value["line"]
                        paths[path] = sorted(set(paths.get(path, []) +
                                                 (lines if isinstance(lines, list) else [lines])))
                    for child in value.values():
                        collect(child, repository)
                elif isinstance(value, list):
                    for child in value:
                        collect(child, repository)

            for category, evidence in categories.items():
                if category == "glossaryIterationReaderKeys":
                    for name in evidence["sharedEvidenceNames"]:
                        for repository, entry in shared[name].items():
                            collect(entry, repository)
                elif category in {"directReaderKeys", "otherReferences"}:
                    for repository, paths in evidence.items():
                        for path, lines in paths.items():
                            collect({"path": path, "line": lines}, repository)
                else:
                    for repository, entries in evidence.items():
                        collect(entries, repository)
            report[section][key] = locations
    report.pop("sharedEvidence", None)
    return report


def build_report(payload, repositories, matches, unresolved, comments=None):
    keys = set(payload["glossary"])
    detected = keys & matches.keys()
    usage = grouped_usage({key: matches[key] for key in detected}, repositories)
    report = {
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "source": {"endpoint": ENDPOINT, "version": payload["version"]},
        "repositories": repositories,
        "counts": {
            "total": len(keys),
            "used": {"total": len(detected), **{name: len(entries) for name, entries in usage.items()}},
            "unused": {
                "noDetectedReference": len(keys - detected),
            },
        },
        "used": report_evidence(keyed_usage(usage)),
        "unused": {key: {"commentReferences": report_evidence((comments or {}).get(key, []))}
                   for key in sorted(keys - detected)},
    }

    return flatten_used_locations(separate_obsolete_used(compact_report(report), payload["glossary"]))


def source_evidence(source_root, location):
    path = unquote(location["artifactLocation"]["uri"])
    relative = Path(path)
    if relative.is_absolute() or ".." in relative.parts:
        raise ValueError(f"Unsafe CodeQL source path: {path}")
    line = location["region"]["startLine"]
    return {"path": path, "line": line}


def read_flow_results(sarif, source_root, repository):
    references = []
    for result in sarif["runs"][0].get("results", []):
        message = result["message"]["text"]
        prefix = "Glossary parameter: "
        if not message.startswith(prefix) or "\n" in message:
            raise ValueError(f"Unexpected flow message: {message}")
        key = message[len(prefix):]
        evidence = source_evidence(source_root, result["locations"][0]["physicalLocation"])
        evidence.update(repository=repository, method="codeqlDataFlow", matchKind="readerDataFlow")
        paths = []
        for code_flow in result.get("codeFlows", []):
            for thread in code_flow["threadFlows"]:
                steps = []
                for entry in thread["locations"]:
                    location = entry["location"]
                    if "physicalLocation" in location:
                        step = source_evidence(source_root, location["physicalLocation"])
                        step["description"] = location.get("message", {}).get("text", "")
                        steps.append(step)
                if steps:
                    paths.append(steps)
        if not paths:
            raise ValueError(f"Missing data-flow path for {key}")
        evidence["dataFlowPaths"] = paths
        evidence["description"] = "A known parameter name can flow through variables or helper calls to this reader. Paths show possible flows, not exhaustive runtime values."
        references.append((key, evidence))
    return references


def analyze_flow(codeql, workdir, source_root, repository):
    output = workdir / "glossary-flow.sarif"
    phrase_audit.run(codeql, "database", "analyze", str(workdir / "db"),
                     str(HERE / "glossary-flow.ql"), "--format=sarif-latest",
                     "--sarif-add-snippets", "--no-group-results",
                     f"--output={output}")
    return read_flow_results(json.loads(output.read_text()), source_root, repository)


def analyze_numbered(codeql, workdir, source_root, repository):
    output = workdir / "glossary-numbered.sarif"
    phrase_audit.run(codeql, "database", "analyze", str(workdir / "db"),
                     str(HERE / "glossary-numbered.ql"), "--format=sarif-latest",
                     "--no-group-results", f"--output={output}")
    references = read_flow_results(json.loads(output.read_text()), source_root, repository)
    if references and repository == "threshold":
        formatter = (source_root / "components/utils.js").read_text()
        expected = 'export function fillNumberLength(n, length) {\n  let str = n.toString();\n  while (str.length < length) str = "0" + str;\n  return str;\n}'
        if expected not in formatter:
            raise RuntimeError("fillNumberLength changed; review numbered-family model")
    for key, evidence in references:
        evidence["matchKind"] = "readerNumberedFamily"
        evidence["method"] = "codeqlNumberedFamily"
        evidence["definition"] = key
        evidence["numberRange"] = {"minimum": 1, "maximum": 99, "digits": 2}
        evidence["description"] = "CodeQL traced a two-digit name constructed in a 1..99 loop to this reader; its @@ glossary definition is used."
        evidence["constructions"] = [path[0] for path in evidence["dataFlowPaths"]]
    return references


def analyze_source_names(codeql, workdir):
    result = workdir / "source-names.bqrs"
    decoded = workdir / "source-names.csv"
    phrase_audit.run(codeql, "query", "run", str(HERE / "glossary-source-names.ql"),
                     f"--database={workdir / 'db'}", f"--output={result}")
    phrase_audit.run(codeql, "bqrs", "decode", str(result), "--format=csv", f"--output={decoded}")
    with decoded.open(newline="", encoding="utf-8") as file:
        return list(csv.reader(file))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--glossary-json", type=Path, help="Use a saved published glossary payload")
    parser.add_argument("--output", type=Path, default=HERE / "glossary-report.json")
    args = parser.parse_args()
    codeql = os.environ.get("CODEQL_BIN", "codeql")
    if args.glossary_json:
        payload = json.loads(args.glossary_json.read_text())
    else:
        metadata = json.loads(phrase_audit.run("curl", "-fLsS", "--retry", "3", ENDPOINT + "?versionOnly=1", capture=True))
        payload = json.loads(phrase_audit.run("curl", "-fLsS", "--retry", "3", ENDPOINT + "?v=" + metadata["version"], capture=True))
        if payload.get("version") != metadata["version"]:
            raise RuntimeError("Glossary version changed during fetch")
    write_key_input(payload["glossary"])
    phrase_audit.run(codeql, "pack", "install", str(HERE))
    repositories, matches, unresolved = {}, defaultdict(list), []
    comments = defaultdict(list)
    with tempfile.TemporaryDirectory(prefix="easyeyes-glossary-codeql-") as temporary:
        workdir = Path(temporary)
        for name, repo, branch, roots in phrase_audit.REPOSITORIES:
            info, source = phrase_audit.snapshot(name, repo, branch, roots, workdir / "sources")
            repositories[name] = info
            rows = phrase_audit.analyze(codeql, source, workdir / name, HERE / "glossary-usage.ql")
            for key, refs in comment_references(analyze_comments(codeql, workdir / name), payload["glossary"], name).items():
                for ref in refs:
                    ref["commit"] = info["commit"]
                comments[key].extend(refs)
            name_rows = analyze_source_names(codeql, workdir / name)
            for key, path, line, kind in rows[1:] + name_rows[1:]:
                evidence = {"repository": name, "path": path, "line": int(line), "method": "codeql", "matchKind": kind}
                if kind == "unresolvedReader":
                    unresolved.append(evidence)
                else:
                    matches[key].append(evidence)
            for key, evidence in analyze_flow(codeql, workdir / name, source, name):
                matches[key].append(evidence)
            numbered_references = analyze_numbered(codeql, workdir / name, source, name)
            resolved_sites = set()
            for key, evidence in numbered_references:
                matches[key].append(evidence)
                resolved_sites.add((name, evidence["path"], evidence["line"]))
            unresolved = [site for site in unresolved if
                          (site["repository"], site["path"], site["line"]) not in resolved_sites]
            if name == "threshold":
                loop_refs = glossary_iteration_references((source / "components/utils.js").read_text(), payload)
                for key, evidence in loop_refs:
                    matches[key].append(evidence)
                loop_sites = {(ref["path"], ref["line"]) for _, ref in loop_refs}
                unresolved = [site for site in unresolved if not
                              (site["repository"] == name and (site["path"], site["line"]) in loop_sites)]
            for site in unresolved:
                if site["repository"] != name:
                    continue
                resolved_keys = sorted({key for key, refs in matches.items() for ref in refs
                                        if ref["matchKind"] == "readerDataFlow" and
                                        ref["repository"] == name and ref["path"] == site["path"] and
                                        ref["line"] == site["line"]})
                if resolved_keys:
                    site["resolvedKeys"] = resolved_keys
                    site["resolution"] = "partial"
            print(f"{name}: {info['sourceFiles']} source files, {len(rows)-1} findings", flush=True)
    report = build_report(payload, repositories, matches, unresolved, comments)
    args.output.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps({"report": str(args.output), **report["counts"]}))


if __name__ == "__main__":
    main()
