name: Analyze International Phrases Used

on: workflow_dispatch

jobs:
  analyze-phrases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          git submodule update --init --recursive
          npm ci
      - name: Run i18n phrase static analysis
        run: |
          cd docs/experiment/threshold
          npm run analyze:phrases
        # env:
        #   NODE_OPTIONS: --no-warnings --input-type=module
