# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Update Phrases and Glossary

on: workflow_dispatch

jobs:
  phrases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set commit account information
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Installations
        run: |
          git submodule update --init --recursive
          npm run setup
      - name: Decrypt credentials
        run: |
          gpg --quiet --batch --yes --passphrase="${{secrets.google_api_pw}}" \
          --output docs/experiment/threshold/server/credentials.json \
          --decrypt docs/experiment/threshold/server/credentials.json.gpg
      - name: Fetch and update phrases
        # continue-on-error: true
        run: |
          cd docs/experiment/threshold
          npm run phrases
          git status
          git add -A
          git commit -m 'github action: update phrases' --no-verify
          git remote set-url origin https://x-access-token:${{secrets.ci_token}}@github.com/EasyEyes/threshold
          git push

          cd ..
          git add -A
          git commit -m 'github action: update phrases' --no-verify
          git remote set-url origin https://x-access-token:${{secrets.ci_token}}@github.com/EasyEyes/threshold-scientist
          git push

          cd ..
          git add -A
          git commit -m 'github action: update phrases' --no-verify
          git remote set-url origin https://x-access-token:${{secrets.ci_token}}@github.com/${{github.repository}}
          git push

  glossary:
    needs: phrases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set commit account information
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Installations
        run: |
          git submodule update --init --recursive
          npm run setup
      - name: Decrypt credentials
        run: |
          gpg --quiet --batch --yes --passphrase="${{secrets.google_api_pw}}" \
          --output docs/experiment/threshold/server/credentials.json \
          --decrypt docs/experiment/threshold/server/credentials.json.gpg
      - name: Fetch and update glossary
        # continue-on-error: true
        run: |
          cd docs/experiment/threshold
          npm run glossary
          git status
          git add -A
          git commit -m 'github action: update glossary' --no-verify
          git remote set-url origin https://x-access-token:${{secrets.ci_token}}@github.com/EasyEyes/threshold
          git push

          cd ..
          git add -A
          git commit -m 'github action: update glossary' --no-verify
          git remote set-url origin https://x-access-token:${{secrets.ci_token}}@github.com/EasyEyes/threshold-scientist
          git push

          cd ..
          git add -A
          git commit -m 'github action: update glossary' --no-verify
          git remote set-url origin https://x-access-token:${{secrets.ci_token}}@github.com/${{github.repository}}
          git push
